### PR TITLE
Release v1.5.0

### PR DESCRIPTION
**Pull request by razwan**
Most notable changes introduced by this release:

- New Block: **Posts Collection**
- New **system** for **organising controls** in **sections** and **tabs**
- New controls for **layout**, **alignment** and **display** for the **Media Card Constellation** block
- Improved style and consistency for **block emphasis level** controls
- Use **Unsplash API** to load placeholders for **Media Card Contellation**, **Gallery of the Stars**, **Hero**, **Slideshow** and **Card** blocks

What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by georgeolaru** [comment]
## Design Customization
I played for a while with the new **Design Customization** options. It's a nice shift and a good starting point that we will build upon. Here are my findings and suggestions for this phase:
1. [ ] I noticed that the **Buttons** block is [not centered](https://user-images.githubusercontent.com/1632775/84130898-842d0200-aa4c-11ea-8f0b-e93b6ef32a9d.png) within the Media Card content or the [Group block](https://user-images.githubusercontent.com/1632775/84146676-bcd8d580-aa64-11ea-9b51-fe7a45db0462.png).
2. [ ] When selecting a block, the Design Customization has a [slide-down animation](https://user-images.githubusercontent.com/1632775/84131858-d28ed080-aa4d-11ea-88a4-086719325265.gif) that it's distracting when moving between blocks – can we show the options instantly?
3. [ ] The "Advanced" section up-and-down movement is distracting [when switching between tabs](https://user-images.githubusercontent.com/1632775/84132096-1d104d00-aa4e-11ea-8af6-7c59e11cad11.gif). Until we find a way to [focus](https://user-images.githubusercontent.com/1632775/84132291-5fd22500-aa4e-11ea-85a9-67c64ed9d0e4.png) solely on the style customizations,  can we hide it when entering a Design Customization section? 

## Cards Collection
1. [ ] **Title Level** option not working unless I [click on cards](https://user-images.githubusercontent.com/1632775/84144309-ba747c80-aa60-11ea-9615-644795e32850.png) individually 
2. [ ] Move **Title Level** and **Content Alignment** option from _Color Contrast_ to _Display_ section
3. [ ] Add a visual hint for **Add Image** option 
4. [ ] When "Content Area" is Moderate or Highlighted, there seem to be a [missing top spacing](https://user-images.githubusercontent.com/1632775/84144601-3242a700-aa61-11ea-8a80-c902dd00f1af.png) for the thumbnail

## Media Card
1. [ ] The [content padding](https://user-images.githubusercontent.com/1632775/84146426-5e135c00-aa64-11ea-9921-0ed77a6bc559.png) variable seems to be different between Front and Back end.


---

**Ideas inbox**
- Elaborate or Refactor the "Spacer" block to use our spacing variables (eg. 1,2,3)

**Comment by madalingorbanescu** [comment]
Hey @razwan,

A lot of things are happening in this PR, so I am going to let my suggestions for every notable change. 

**Image placeholder using Unsplash API**
Everything is working smoothly, but the loaded images are too big. For Hero and Slideshow blocks, we should use images with a resolution bigger than 1080p, but for Galleries and Cards, we should not load images bigger than 1000px width. Currently, I see that we load images with a resolution of 4000x4000, and images are having a size of 3-4MB, which is a lot.

**Improved style and consistency for block emphasis level controls**
You did an excellent job with the block emphasis controls. Everything is working great, except for a few inconsistencies on mobiles. For example, on the Media card block, when we are using Block Emphasis on Moderate or Highlighted, we can also set Emphasis area width, which is awesome. On a desktop, [it looks great](https://user-images.githubusercontent.com/46342490/85523649-f0dcfa80-b60f-11ea-887f-e12168f187b8.png), however, on mobiles is [not looking so good](https://user-images.githubusercontent.com/46342490/85523954-487b6600-b610-11ea-8e4d-ff3878b78c24.png). I think the Emphasis Area Moderate or Highlighted should be 100% all the time on mobiles.

On a Cards Collection with Block Emphasis set on Highlighted, there is a problem with [Cards Collection Title and Description color on mobiles](https://user-images.githubusercontent.com/46342490/85524614-fedf4b00-b610-11ea-80a2-227b031de2d2.png). Another possible issue is that a Cards Collection with Block Emphasis on Highlighted and Content Emphasis on Basic is different on mobile than a Cards Collection with Block Emphasis on Highlighted and Content Emphasis on Highlighted. Here is a short video: https://share.getcloudapp.com/Z4uYKKK7

**New controls for layout, alignment, and display for the Media Card Constellation block**
Nothing wrong here, all controls are working well in editor and frontend.

**New system for organizing controls in sections and tabs**
The new system worked really well and I couldn't find any issues. It took me a few minutes to get used to it.

**New Block: Posts Collection**
I am not sure if the Content Alignment option should also be applied to Cards Collection Title and Description. Block Emphasis Moderate and Highlighted is missing padding-top and bottom in editor ([example](https://share.getcloudapp.com/2Nu5qqg6)). Here we have the same problem with [Cards Collection Title and Description color on mobiles](https://user-images.githubusercontent.com/46342490/85524614-fedf4b00-b610-11ea-80a2-227b031de2d2.png) like the on with Cards Collection, probably because we are using the same component.

When I am adding a second Posts Collection Block, the block is not displaying the latest posts. However, it is showing the latest posts after the posts from the first Posts Collection Block, if that makes sense. 
If I am having two Posts collection blocks showing the latest posts on the same page and on the first one I am increasing the posts that are shown, the posts from the second block are somehow transferred to the first block. I know that this may not be clear, so here is a [short video](https://share.getcloudapp.com/2Nu5qlQo). This issue may be related to the previous one.

In editor we should remove the [`margin-bottom` applied on paragraph inside `.novablocks-card__description`](https://user-images.githubusercontent.com/46342490/85545752-e7aa5880-b624-11ea-8bd5-1862f1194558.png)

Another thing about the Title Level. I think I had asked you some time ago about this, but I cannot remember your answer. With that option, we want to change the size and style of the title or just size? Because now, when I am selecting H3, it's changing its color ([example](https://share.getcloudapp.com/kpu5DnnO)).

Let me know if I can help you with any of these issues.

**Comment by madalingorbanescu** [comment]
While testing the Cards Collection Block I saw that when we are applying Emphasis on Block Level, we are not adding padding-top and padding-bottom on the block. 

@georgeolaru I remember that on the Media Card Block Emphasis —  Moderate or Highlighted was coming with a padding-top and padding-bottom and I think we should keep this pattern because without padding the result is this:
image
While with padding is looking like this:
image

If it's possible, I think we should set the minimum to 1 for Block Spacing —  top and bottom, while Block Emphasis is set on Moderate or Highlighted.

What do you think @razwan @georgeolaru?

**Comment by andreiungurianu** [comment]
Hello,

I've teste the new changes and here are some of the things I've noticed during my tests. I read what @madalingorbanescu published and I hope I will not overlap with his suggestions.

I'll take the blocks one by one and lay out the things I discovered:

**Media Card**

- After the update, all my previous media cards have changed their top and bottom spacing. To achieve the previous default spacing I have to go the Color Contrast settings and change the Content Area Emphasis level from Basic to Moderate
Image 2020-07-15 at 2 58 22 PM
- When I add a new media card, the button area has extra spacing in the Gutenberg Editor - 
Image 2020-07-15 at 12 22 17 PM
- Overlaping options do not show the same behaviour in the Gutenberg editor and do not display the same way as in the live website - https://share.getcloudapp.com/WnubnEro. This makes using the overlap features really difficult because it's hard to tell if my settings do what I want them do to
- _The Overlap 2 / Centered_ and _Overlap 3 / Bottom Anchoring_ reveal an empty white space at the top when I have Block Emphasis level set to Moderate. Maybe I don't understand the spacing options, so please take a look and see if it's on purpose or not. Video - https://share.getcloudapp.com/jkuQklwd
- Choosing the _Overlap 1 / Top Anchoring_ options adds an Moderate Block Emphasis level to the block that was not previously selected. The other overlap presets do not have the same behaviour. Video - https://share.getcloudapp.com/9Zujpjly

**Slideshow Block**

- Changing the Minimum Height in the Layout options to Auto makes the slideshow disappear in the Gutenberg editor. Video - https://share.getcloudapp.com/12uN8N04
- When I have a Maps block before or after the Slideshow block, there’s an extra empty space between them. Video -https://share.getcloudapp.com/qGuKGKGb

**Hero Block** 

- While using the Doppler effect and scrolling back to top, there’s a small jump of the background image - https://share.getcloudapp.com/Wnubndbq

**Posts Collection Blocks**

- Enabling the Subtitle actually means enabling the display of the post category. We should consider renaming this option to “Category"

**Some general feedback:**

After playing around with many of the new options, I always found that I wanted to reset what I was doing, but not all options have a “Default” setting. The only option that has a default setting is the “Space and Sizing” section. 

A few examples where I needed it:
- Visual Balance tab - after I played around in the “Settings” tab, I had a hard time getting back to the default Content Area Width and Layout Gutter. 
- Media Composition - The Cloud Atlas options would make sense to be called “Default” because it is the default option for the media, and one that most people use.

**Comment by georgeolaru** [comment]
@andreiungurianu thanks for testing and for reporting the issues that you encounter! Let's fix the bugs first and postpone the suggestions for when we will do the first iterations (eg. _Posts Collection Blocks_ and _Some general feedback_)

**Comment by andreiungurianu** [comment]
@georgeolaru sounds like a great plan.

**Pull request merged**
