### PR TITLE
Release 1.6.0

### PR DESCRIPTION
**Pull request by razwan**
* Add parametric layout generation controls for the Posts Collection block
* Add video support for the Media Card Constellation block
* Improve performance by splitting and enqueueing only for blocks that are used on a page

### CODE REVIEW

**Comment by madalingorbanescu** [comment]
Hey @razwan,

Here are some issues that I've found out after going through all Rosa2 pages and adding all blocks:
- [ ] Cards Collection block is not working. When I am trying to add this block, I am getting the following error: _This block has encountered an error and cannot be previewed._
- [ ] Map of The World field and button alignment issues: https://share.getcloudapp.com/4guJzREz
- [ ] Media Card Blocks that have been added before these changes are missing their images.
- [ ] OpenTable block that has been added before these changes is not showing up.

**Comment by madalingorbanescu** [comment]
See [here](https://github.com/pixelgrade/rosa2/issues/165#issuecomment-702694753) an explanation for the problems on Hover Menu items.

**Comment by andreiungurianu** [comment]
Hello, 

I've tested the Posts collection block and this is my general impression regarding it, along with a few issues I've discovered.

First off, I find this block to be amazing. It has a lot of customization options and ways you can tweak and turn the posts and achieve a pleasant result. The layout it generates are modern and is really one of the most versatile posts block out there, for sure. It gives the user control over everything.

The only thing that I haven't managed to wrap my head around were the options from Grid Layout -> Settings. There are a lot of controls, and that's a blessing and a curse. What I failed to understand is the logic behind them, which in turn stopped me from being able to have a layout plan and twisting and turning these options until I receive the result I want. Even the columns and rows options are confuzing in terms of they are supposed to change. I spent more than 30 min playing with these options, but everytime the end results seemed random. The naming of the options didn't offer more clues, and I ended up just ignoring them and just drag each option left and right. If my goal would have been to play around until I stumble onto something I like, that would be great. If I have a goal in mind - even something small like not displaying a certain row, I would not be able to figure out how to do it. 

On the other side of the spectrum, the presets you guys created for the Grid Layout are simply awesome. 👏 They manage to give me a lot of creative layouts and I had plenty of options to choose from. I, for one, would probably only use the layout customization found here, since going into the settings (aka the advanced panel) will just confuse things for me.

Overall, I think this block is going to be very useful for users and I want to congratulate everyone involved in designing, creating, and testing it—@georgeolaru @razwan @madalingorbanescu 👏👏👏

Here are a few suggestion that would have made the block customization easier for me:

- I think the Block Module settings should come first with the options in this order: _Content Filter_ then _Display_. It makes more sense to me to first choose what articles I want displayed and the type of meta, images, subtitles to show, than to start changing the layout

- The “Auto-count Items Number” option from Grid Layout -> Settings could benefit from more exposure, since it's a great option that will make some of the preset layouts look better. I would see it place either in the _Grid Layout Presets_ area or in the _Content Filter_  options, under the _Number of Items_ option.

- It would be nice to not have a link on the excerpt text, just on the title and image

**Now, here are a few issues that I encountered:**

**General**

- [ ] The post collection subtitle can't be easily selected. It seems like the area where I need to click is just above the area where the text is displayed - [Subtitle issue.mp4.zip](https://github.com/pixelgrade/nova-blocks/files/5317862/Subtitle.issue.mp4.zip)

- [ ] The Post collection title link does not remain Saved - [Title not saving.mp4.zip](https://github.com/pixelgrade/nova-blocks/files/5317873/Title.not.saving.mp4.zip)

**Grid Layout**

- [ ] Posts title are too narrow and have different alignment in Editor vs Live - [Different alignment title editor vs live.mp4.zip](https://github.com/pixelgrade/nova-blocks/files/5317875/Different.alignment.title.editor.vs.live.mp4.zip)

- [ ] In the Popper Preset - There's a blog post at the bottom that might look better if it was stretched up to the right side. 
[Popper Preset bottom post alignment.png.zip](https://github.com/pixelgrade/nova-blocks/files/5317900/Popper.Preset.bottom.post.alignment.png.zip). 

- [ ] Asimov, Orwell, Destoevsky Presets - the scroll effect works in editor and not in live 
[Problem with presets scroll in live website.gif.zip](https://github.com/pixelgrade/nova-blocks/files/5317904/Problem.with.presets.scroll.in.live.website.gif.zip)

- [ ] In Grid Layout -> Settings, while in Classic Mode, there’s a Landscape option - I was expecting to have the images go Landscape. Something different happens (not sure what) so the naming is confuzing. 
[Portrait and landscape in Grid layout.gif.zip](https://github.com/pixelgrade/nova-blocks/files/5317920/Portrait.and.landscape.in.Grid.layout.gif.zip)

**Card Details**

- [ ] The Thumbnail aspect Ratio are looking “disabled” when I first open the settings, but if I click on them, they get re-enabled - [Card Details option.gif.zip](https://github.com/pixelgrade/nova-blocks/files/5317985/Card.Details.option.gif.zip)


**Color Contrast**

- [ ] The meta information below the featured image (date, title, excerpt) are aligned differently in the editor vs live 
[Meta alignment editor vs live.png.zip](https://github.com/pixelgrade/nova-blocks/files/5317932/Meta.alignment.editor.vs.live.png.zip)

**Comment by razwan** [comment]
Hey @andreiungurianu!

Thanks for the time spent on testing this. Your findings and feedback is very important in the process of implementing and shipping this issue. Also thank you for the in-depth feedback you gave. It helps us understand how someone would approach this on their first encounter. 👏 👏 👏 

I went over the things you mentioned and fixed most of the things you pointed out. The other ones are just my bad because I didn't give you the proper version of Rosa2 to work with. The nice-to-haves will stay in the back of our minds for future updates.

Regarding the 'Settings' tab, I would say that's the intended behaviour. We wanted the ability to create both simple and complex layouts with multiple levels of hierarchy. However we expected to have a higher degree of randomness than the Advanced Gallery. A degree a randomness doesn't mean that the layouts are random at all. We have to be able to obtain the same layout for the same input. There is also a bit of post processing we do after the grid is generated to make sure that the layout is not overly complicated and there aren't too many areas. This can add to the apparent randomness when either nothing or too much is happening when fidgeting with the controls in the settings tab.

The fact is that the presets tab should be more than enough for someone who doesn't want to bother with the complexity of the settings tab. But our bet is that the settings that would spark curiosity for those who find it.

We're just a few tweaks away of shipping this awesome feature.

**Comment by andreiungurianu** [comment]
Hey @razwan - thanks for your feedback and futher clarifications regarding the intent behind the way this block looks and behaves. I'm glad that I could contribute and I can't wait to see it in action and hear what our customers think about. I'm sure they will be impressed.

**Pull request merged**
