### PR TITLE
Add Cards Collection blocks

### PR DESCRIPTION
**Pull request by razwan**
**Description**
Added two new blocks as described in #105 
- Cards Collection
- Card

Many aspects have been discussed in previous issues and pull requests. This pull request should act as a final review of the blocks before flagging them as ready for shipping.

**Types of changes**
What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by madalingorbanescu** [comment]
It looks like something is affecting Media Card layout.
On master:
image
On this branch:
image

The problem is that the padding on `novablocks-block__content` is 0.

**Comment by madalingorbanescu** [comment]
There is a problem with spacings on frontend:
spacings

**Comment by razwan** [comment]
> It looks like something is affecting Media Card layout.

We may address Media Card issues when we integrate the Advanced Gallery component

> There is a problem with spacings on frontend:

Please have rosa2 on the `novablocks-cards` branch

**Comment by georgeolaru** [comment]
I took an in-depth review and here are my insights:

### Collection Title / Subtitle
- When inserting the block I would disable by-default the "Subtitle" and "Meta" fields 
- It would be great to find a way to make the "Insert New Card" area to not interfere with the layout. Now it's taking a little bit too much space: https://share.getcloudapp.com/GGuNOGEK
- There is too much spacing between Collection Title and Subtitle – it looks better if the Collection Subtitle paragraph would have the margin sized in half: https://share.getcloudapp.com/JruWdrL5
- The Collection Subtitle style seems to require the "is-style-lead" class to show as a lead.
- The Collection Subtitle could have a narrower size. I removed the "alignwide" class and it looks better: https://share.getcloudapp.com/z8uXNePm
### Cards
- A newly added card (4th) seems to not take into consideration the disabled fields of Meta and Subtitle: https://share.getcloudapp.com/7KuR7KoP
### Frontend
- There seem to be some small inconsistencies with the Frontend (the container sizing it might be to the "Insert New Card" button): https://share.getcloudapp.com/9ZuAwZKr
- Mobile: the Emphasis Levels background seems to not be taken on the frontend and mobile: https://share.getcloudapp.com/nOuNA02w

---

Other than this, everything else looks great! Cannot wait to release this 🚀

**Comment by madalingorbanescu** [comment]
Responsive issues:
- When I have 3 cards added, this is what is happening between 768px and 1035px: https://share.getcloudapp.com/WnuNLjoN
- When I have 4 cards added, the layout is broken on frontend: https://share.getcloudapp.com/8LuJR8BN, something similar is happening with 3 cards and Content Area set on Moderate or Highlighted: https://share.getcloudapp.com/7KuR7OgR. Also, columns are not equally on the frontend.
- If I am choosing to use H3 as Title Level it will have the same color as the subtitle: https://share.getcloudapp.com/eDuxmqv4
- The subtitle should not be the same color as the title when the Content Area emphasis level is set on Highlighted. The same thing applies when Block Area emphasis level is Highlighted: https://share.getcloudapp.com/Z4u5Qg5q

**Comment by georgeolaru** [comment]
@madalingorbanescu The points 3 and 4 are intended this way as the cards headings (title and subtitle) are lowered levels of the block main title. The decision was made here: https://github.com/pixelgrade/nova-blocks/issues/105#issuecomment-603866896

**Pull request merged**
