### PR TITLE
Add Posts Collection Block

### PR DESCRIPTION
**Pull request by razwan**
**Description**
Broke the **Card Collection** block into multiple components and reused them for this **Posts Collection** block

**Types of changes**
What types of changes does your code introduce?
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

### CODE REVIEW

**Comment by madalingorbanescu** [comment]
The block looks great and I think that it's going to be really useful 🎉
While I've been testing the block I saw a few things that we can improve:
1) We have a title option that is affecting both: Collection Title and Post Title and besides that, the Post Title is changing its color. I am pretty sure that the changing color is a small issue, but regarding the fact, that it is applied to Collection Title and Post Title I am not sure. This is the desired behavior? Another problem I saw is how we change the markup, based on Title Level. On Collection Title the [heading is changed from h2 to h3](https://share.getcloudapp.com/geuWwEAO), which is good but on Post Title, [Title Level H2 is rendered as H3 and H3 is rendered as H4](https://share.getcloudapp.com/jkulQAmw). 

2) On Cards Collection the user can change button style and can modify that Read More text. On this block, the user is stuck with the Primary Button style, and that Read More Text. I would consider a new option for Button Styles, and text input, that will let the user change that Read More Text.

**Comment by razwan** [comment]
I've been working on creating a more flexible panel for controlling the source for the cards. It's missing the ordering feature right now but I don't want to get too much ahead before I gather some feedback. 

The way I'm building it right now you can only selected a taxonomy exclusively and maybe we could transform the terms select into one that allows multiple choice. 

I would vote for this implementation because it should work for any other post type or taxonomy. However, this doesn't cover more complex filtering scenarios like "query all posts from the **news** category tagged **featured**"

Screen Recording 2020-04-24 at 03 39 PM

We could also go for the more straightforward way like we did for the widgets we used in **Felt** but I thinks it is quite limiting and we could miss some opportunities there.

Screenshot 2020-04-24 at 15 44 26


@georgeolaru what do you think?

**Comment by madalingorbanescu** [comment]
Hey @razwan,

While testing the Posts Collection Block, I've found the next issues:
- [ ] PHP Notice: Undefined index: postsToShow in /Users/madalin/Local/novablocks/app/public/wp-content/plugins/nova-blocks/lib/extras.php on line 1158
- [ ] Excerpt is not showing in the editor for some articles: [editor](https://user-images.githubusercontent.com/46342490/82789871-b7c83380-9e73-11ea-9d5d-7643c970fc54.png) vs [frontend](https://user-images.githubusercontent.com/46342490/82789903-c878a980-9e73-11ea-829a-821db86893bc.png).

Also, I saw a few things that can be improved:
- [ ] Add a link on the article date and category.
- [ ] Layout option min should be equal with min number of items.

You did a great job with the filtering system 🚀

**Comment by georgeolaru** [comment]
- [ ] Using [Felt](https://demos.pixelgrade.com/felt/) cards as a reference, a link over the card could be useful when the "read more" buttons are hidden:
image

**Pull request merged**
